favicon:
  enable: true
  icon: /profile/favicon.png
  touch_icon: /profile/favicon.png

avatar:
  author_photo: /profile/avatar.png
  author_nickname: GGos3
  path: /

gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

comments:
  enable: false

navbar:
  - name: Home
    enable: true
    path: /
    key: home
  - name: Archives
    enable: true
    path: /archives/
    key: archives
  - name: Categories
    enable: false
    path: /categories/
    key: categories
  - name: Tags
    enable: false
    path: /tags/
    key: tags
  - name: Friends
    enable: false
    path: /friends/
    key: friends
  - name: About
    enable: false
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  - nickname: Zcheng
    site: https://zcheng.site/
    meta:
  - nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  social:
    - name: github
      icon: github
      path: https://github.com/ggos3

  more:
    - name: Copyright © {thisYear} Oranges
      path: https://github.com/zchengsite/hexo-theme-oranges
    - name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges
  views:
    enable: false
    provider: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
    item:
      - enable: true
        id: busuanzi_value_site_pv
        name: 本站总访问量
        unit: 次
      - enable: true
        id: busuanzi_value_page_pv
        name: 本文总阅读量
        unit: 次
      - enable: true
        id: busuanzi_value_site_uv
        name: 本站访客数
        unit: 人

search:
  enable: true
  placeholder:

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

codeBlock:
  style: "mac-black"
  copy:
    enable: true

mathjax:
  enable: true

cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: false
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js

# Google Analytics Traking ID
google_analytics: [G-V1NQGK9KYL]

# 主题色
themeColor: "#c5c1ec"
