# 相关配置说明
# favicon: 网站图标
# avatar: 主题用户头像与昵称
# rss: rss订阅
# gtag: Google 分析
# comments: 文章评论系统
# gitalk
# disqus
# navbar: 主题页面导航栏
# catalog: 文章目录
# prevnext: 文章末尾的上一页与下一页
# friends: 友链
# footer: 页脚信息
# search: 文章搜索
# colorSwitch: 深/浅配色切换
# postShare: 文章分享
# codeBlock: 代码块配置

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /profile/favicon.png
  touch_icon: /profile/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /profile/avatar.png
  author_nickname: GGos3
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: true
    clientID: ecd6bf5b4d0f89e7dd49
    clientSecret: 071486a21a327eabb148bf4494b8b2c9d434d42a
    repo: gitalk
    owner: ggos3
    admin: ggos3
    id: location.pathname
    distractionFreeMode: true

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io

  # waline https://waline.js.org
  waline:
    enable: false
    serverURL:

# 主题页面导航栏
navbar:
  - name: Home
    enable: true
    path: /
    key: home
  - name: Archives
    enable: true
    path: /archives/
    key: archives
  - name: Categories
    enable: true
    path: /categories/
    key: categories
  - name: Tags
    enable: false
    path: /tags/
    key: tags
  - name: Friends
    enable: false
    path: /friends/
    key: friends
  - name: About
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  - nickname: Zcheng
    site: https://zcheng.site/
    meta:
  - nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址

    # 按需取消注释以启用
    - name: github
      icon: github
      path: https://github.com/ggos3
    # -
    #   name: email
    #   icon: envelope
    #   path:
    # -
    #   name: facebook
    #   icon: facebooksquare
    #   path:
    # -
    #   name: twitter
    #   icon: twitter
    #   path:
    # -
    #   name: wechat
    #   icon: wechat
    #   path:
    # -
    #   name: weibo
    #   icon: weibo
    #   path:
    # -
    #   # rss需安装 hexo-generator-feed 插件
    #   # 具体参照https://github.com/hexojs/hexo-generator-feed
    #   name: rss
    #   icon: rss
    #   path: /atom.xml

  more:
    # 支持变量显示，可自定义扩展，具体见主题/layout/_partial/footer.ejs
    # 一般用来显示根据各种场景需要切换的文本，如时间年份
    # 如：{thisYear} 会被替换为今年年份
    - name: Copyright © {thisYear} Oranges
      path: https://github.com/zchengsite/hexo-theme-oranges
    - name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

  # 浏览量统计
  # http://busuanzi.ibruce.info/
  views:
    enable: false
    provider: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
    item:
      - enable: true
        id: busuanzi_value_site_pv
        name: 本站总访问量
        unit: 次
      - enable: true
        id: busuanzi_value_page_pv
        name: 本文总阅读量
        unit: 次
      - enable: true
        id: busuanzi_value_site_uv
        name: 本站访客数
        unit: 人

# 文章搜索
search:
  enable: true
  placeholder:

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

# 代码块配置
codeBlock:
  # 代码块风格，默认normal
  # 可选：默认风格'normal'；mac黑色风格：'mac-black'
  style: "mac-black"
  # 代码复制
  copy:
    enable: true

# MathJax Support
# 数学公式支持
mathjax:
  enable: true

# cdn配置，默认关闭，如需启动，先确保对应插件版本cdn资源可用后再开启
# 如资源加载失败，可替换cdn提供商或设置enable:false默认走本地资源
# 也可使用自己的cdn服务，资源在/theme/oranges/source/plugins下
cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # LaTeX 公式
  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  # 代码块复制
  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  # 评论系统
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: false
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js

# 主题色
themeColor: "#808080"
